title: Matheus Batista # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Estudante de Engenharia Elétrica se aventurando no mundo de Ciência de Dados, Machine learning e Deep learning.
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/matheus-amorimb/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors: '#0d1b2a'
